pipeline {
    agent any
    environment {
        MSBUILD_HOME = tool name: "msbuild", type: "msbuild"
    }
    options {
    timeout(time: 40, unit: 'SECONDS') 
    }
	stages {
		stage('Checkout') {
			steps{
				git 'https://github.com/ahmadgbg/WebTeam6.git'
		
			}
		}
		stage('Build') {
			steps{
				sh 'dotnet restore WebTeam6.sln'
				sh('\"%MSBUILD_HOME%/msbuild.exe\" WebTeam6.sln')
			}
		}
		stage('Run'){
			parallel{
				stage('Run Website'){
					steps{
						sh 'dotnet run'
					}
				}
				stage('Robot') {
					steps {
					    sleep 10
						sh 'robot -d results --variable BROWSER:headlesschrome "Test/Test Cases/web6test.robot"'
					}
					post {
						always {
							script {
								step(
									 [
									   $class              : 'RobotPublisher',
									   outputPath          : 'results',
									   outputFileName      : '**/output.xml',
									   reportFileName      : '**/report.html',
									   logFileName         : '**/log.html',
									   disableArchiveOutput: false,
									   passThreshold       : 50,
									   unstableThreshold   : 40,
									   otherFiles          : "**/*.png,**/*.jpg",
									 ]
								)	
							}
						}
					}
				}
			}
                
		}
	}
}