pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps{
                git branch: 'WEB6-41-UserRegistration', url: 'https://github.com/ahmadgbg/WebTeam6.git'

            }
        }
        stage('Build') {
            steps{
                bat 'dotnet build'
            }
        }
        stage('Run Website'){
            steps{
                    bat 'START /B dotnet run'
            }
        }
        stage('Robot') {
            steps {
                    sleep 10
                    bat 'robot -d results --variable BROWSER:headlesschrome "Test/TestCases/web6test.robot"'
            }
            post {
                always {
                    script {
                        step(
                             [
                               $class              : 'RobotPublisher',
                               outputPath          : 'results',
                               outputFileName      : '**/output.xml',
                               reportFileName      : '**/report.html',
                               logFileName         : '**/log.html',
                               disableArchiveOutput: false,
                               passThreshold       : 50,
                               unstableThreshold   : 40,
                               otherFiles          : "**/*.png,**/*.jpg",
                            ]
                        )
                    }
                }
            }

        }
    }
    post{
        always{
            bat 'TASKKILL /F /IM dotnet.exe'
        }
    }
}